<div class="page-header">
    <div class="pull-left">
        <h1>Màu sản phẩm</h1>
    </div>
</div>


<div class="row-fluid">
    <div class="span12">
        <div class="box box-bordered box-color">
            <div class="box-title">
                <h3><i class="icon-edit"></i> <?php echo $actionTitle;?></h3>
            </div>
            <div class="box-content nopadding">
                <?php
                $form->setAttributes(['action' => '', 'class' => 'form-horizontal form-bordered', 'id' => 'frm']);
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>

                <div class="control-group">
                    <?php echo $this->formLabel($form->get('color_name')); ?>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('color_name')); ?>
                        <?php echo $this->formElementErrors($form->get('color_name'), array('class' => 'error-message')); ?>
                    </div>
                </div>



                <div class="control-group">
                    <?php echo $this->formLabel($form->get('color_picture')); ?>
                    <div class="controls">


                        <?php echo $this->formElementErrors($form->get('color_picture'), array('class' => 'error-message')); ?>

                        <div class="fileupload fileupload-new" data-provides="fileupload">
                            <div class="fileupload-new thumbnail" style="width: 32px; height: 32px;">
                                <?php if (isset($record) && $record['color_picture'] != '') {?>
                                    <img title="Click để xóa" id="picture" onclick="deletePicture(<?php echo $record['color_id'];?>)" style="width: 32px; height: 32px; cursor: pointer" class="img-thumbnail" src="<?php echo $this->basePath('pictures/' . $record['color_picture']);?>" />
                                <?php }?>
                            </div>
                            <div class="fileupload-preview fileupload-exists thumbnail" style="width: 32px; height: 32px;"></div>
                            <div>
                                <span class="btn btn-file">
                                    <span class="fileupload-new">Chọn hình</span><span class="fileupload-exists">Thay đổi</span>
                                    <?php echo $this->formElement($form->get('color_picture')); ?></span>
                                <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Xóa</a>
                            </div>
                        </div>
                        <span class="help-block">width: 32; height: 32 (pixel)</span>

                    </div>
                </div>

                <div class="control-group">
                    <?php echo $this->formLabel($form->get('color_status')); ?>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('color_status')); ?>
                        <?php echo $this->formElementErrors($form->get('color_status'), array('class' => 'error-message')); ?>
                    </div>
                </div>


                <div class="form-actions">
                    <?php echo $this->formSubmit($form->get('submit')); ?>
                    <?php echo $this->formHidden($form->get('csrf')); ?>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>


<script>
    $(document).ready(function(){
        $("#frm").validate({
            rules: {
                color_name: 'required',
            },
            messages: {
                color_name: 'Vui lòng nhập thông tin',
            }
        });
    });

    function deletePicture(id) {
        if (confirm('Bạn có muốn xóa?')) {
            $.ajax({
                url: '<?php echo $this->url('admin/color', array('action' => 'delete-picture'));?>',
                type: 'post',
                data: {id: id},
                success: function (response) {
                    data = jQuery.parseJSON(response);
                    if (data.return == 1) {
                        $('#picture').remove();
                    }
                }
            });
        }
    }
</script>