<div class="page-header">
    <div class="pull-left">
        <h1>Email khách hàng đăng ký nhận tin</h1>
    </div>
</div>

<div class="pull-right" style="margin-bottom: 10px">
    <form action="<?php echo $this->url('admin/email-customer', array('action' => 'export')); ?>" method="post" target="_blank">
    <input type="submit" class="btn btn-success" value="Xuất Excel">
    </form>
</div>

<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-nomargin table-striped table-colored-header">
                    <thead>
                    <tr>
                        <th>Email</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($records as $record) { ?>
                        <tr>
                            <td><strong><?php echo $this->escapeHtml($record['email_customer_name']); ?></strong></td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
                <div class="form-actions no-margin-bottom" style="text-align:right;">
                    <?php echo $this->paginationControl($records, 'sliding', 'admin/partial/paginator', array('url' => $this->url('admin/email-customer'),)); ?>
                </div>

            </div>
        </div>
    </div>
</div>