<div class="page-header">
    <div class="pull-left">
        <h1>Trang nội dung</h1>
    </div>
</div>

<div class="pull-right" style="margin-bottom: 10px">
    <input type="button"
           onclick="location.href='<?php echo $this->url('admin/page', array('action' => 'add')); ?>'"
           class="btn btn-primary" value="Thêm">
</div>

<div class="col-lg-12">
<?php echo $this->flashMessenger()->renderCurrent('default', array('alert', 'alert-success')); ?>
</div>

<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-nomargin table-striped table-colored-header">
                    <thead>
                    <tr>
                        <th>Tiêu đề</th>
                        <th>Trạng thái</th>
                        <th>Chức năng</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($records as $record) { ?>
                        <tr style="background: <?php echo $statusColor[$record['status']]; ?>">
                            <td><strong><?php echo $this->escapeHtml($record['page_title']); ?></strong></td>
                            <td><?php echo $status[$record['page_status']]; ?></td>
                            <td>
                                <a href="<?php echo $this->url('admin/page', array('action' => 'edit'), array('query' => array('id' => $record['page_id']))); ?>">
                                    <i class="icon-edit"></i>
                                </a>
                                <a onclick="return confirmDelete()"
                                   href="<?php echo $this->url('admin/page', array('action' => 'delete'), array('query' => array('id' => $record['page_id']))); ?>">
                                    <i class="icon-remove"></i>
                                </a>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
                <div class="form-actions no-margin-bottom" style="text-align:right;">
                    <?php echo $this->paginationControl($records, 'sliding', 'admin/partial/paginator', array('url' => $this->url('admin/page'),)); ?>
                </div>

            </div>
        </div>
    </div>
</div>

<script>
    function confirmDelete() {
        if (!confirm('Bạn có chắc chắn muốn xóa?')) {
            return false;
        }
    }
</script>
