<?php foreach ($products as $v) { ?>
    <div class="product-index col-lg-4 col-md-4 col-sm-6 col-xs-12"
         data-alpha="Belted Cotton-silk Pencil Dress" data-price="120000">
<!--        --><?php //if ($v['product_type_new'] == 1) { ?>
<!--            <div class="new icn">Mới</div>-->
<!--        --><?php //} ?>
<!--        --><?php //if ($v['product_type_sale'] == 1) { ?>
<!--            <div class="sale-item icn">Sale</div>-->
<!--        --><?php //} ?>
        <a href="<?php echo $this->url('home-product-detail', array('name' => $this->functions()->formatTitle($v['product_name']), 'id' => $v['product_id'])); ?>">
            <?php
            if ($v['product_picture'] != '') {?>
                <img class="img-responsive" id="product-item-picture-<?php echo $v['product_id'];?>" src="<?php echo $this->serverUrl() . '/public/thumbs/timthumb.php?src=' . $this->basePath() . '/public/pictures/' . $v['product_picture']; ?>&w=375&h=375"
                 alt="<?php echo $this->escapeHtml($v['product_name']); ?>">
            <?php } else {?>
                <img class="img-responsive" id="product-item-picture-<?php echo $v['product_id'];?>" src="<?php echo $this->serverUrl() . '/public/thumbs/timthumb.php?src=' . $this->basePath() . '/public/img/nimg.jpg'; ?>&w=375&h=375"
                     alt="<?php echo $this->escapeHtml($v['product_name']); ?>">
            <?php }?>


        </a>

        <div class="product-info">
            <div class="color">
                <?php foreach($v['product_detail'] as $vv) {?>
                <label class="product-item-change-color"
                    <?php
                    if ($v['product_picture'] != '') {?>
                       data-img="<?php echo $this->serverUrl() . '/public/thumbs/timthumb.php?src=' . $this->basePath() . '/public/pictures/' . $vv['product_picture_name']; ?>&w=375&h=375"
                    <?php } else {?>
                        data-img="<?php echo $this->serverUrl() . '/public/thumbs/timthumb.php?src=' . $this->basePath() . '/public/img/nimg.jpg';?>&w=375&h=375"
                    <?php }?>
                       data-id="<?php echo $v['product_id'];?>" style="background: url('<?php echo $this->serverUrl() . '/public/thumbs/timthumb.php?src=' . $this->basePath() . '/public/pictures/' . $vv['color_picture']; ?>')"></label>
                <?php }?>

            </div>
            <a href="<?php echo $this->url('home-product-detail', array('name' => $this->functions()->formatTitle($v['product_name']), 'id' => $v['product_id'])); ?>">

                <div class="prod-title"><?php echo $this->escapeHtml($v['product_name']); ?></div>
            </a>

            <div class="price">
<!--                --><?php //if ($v['product_type_sale'] == 1) { ?>
<!--                    <div class="onsale"><span class="money">--><?php //echo $this->currency($v['product_price']);?><!-- VND</span></div>-->
<!--                    <div class="was"><span class="money">--><?php //echo $this->currency($v['product_price_old']);?><!-- VND</span></div>-->
<!--                --><?php //} else {?>
                    <div class="prod-price"><span class="money"><?php echo $this->currency($v['product_price']);?> VND</span></div>
<!--                --><?php //}?>
            </div>
        </div>
    </div>
<?php } ?>
