<div class="page-header">
    <div class="pull-left">
        <h1>Liên hệ</h1>
    </div>
</div>

<div class="pull-right" style="margin-bottom: 10px">
    <form action="<?php echo $this->url('admin/contact', array('action' => 'export')); ?>" method="post" target="_blank">
    <input type="submit" class="btn btn-success" value="Xuất Excel">
    </form>
</div>

<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-nomargin table-striped table-colored-header">
                    <thead>
                    <tr>
                        <th>Tên</th>
                        <th>Email</th>
                        <th>Điện thoại</th>
                        <th>Lời nhắn</th>
                        <th>Chức năng</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($records as $record) { ?>
                        <tr>
                            <td><?php echo $this->escapeHtml($record['contact_fullname']); ?></td>
                            <td><?php echo $this->escapeHtml($record['contact_email']); ?></td>
                            <td><?php echo $this->escapeHtml($record['contact_phone']); ?></td>
                            <td><?php echo $this->escapeHtml($record['contact_content']); ?></td>
                            <td>
                                <a onclick="return confirmDelete()"
                                   href="<?php echo $this->url('admin/contact', array('action' => 'delete'), array('query' => array('id' => $record['contact_id']))); ?>">
                                    <i class="icon-remove"></i>
                                </a>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
                <div class="form-actions no-margin-bottom" style="text-align:right;">
                    <?php echo $this->paginationControl($records, 'sliding', 'admin/partial/paginator', array('url' => $this->url('admin/email-customer'),)); ?>
                </div>

            </div>
        </div>
    </div>
</div>