<div class="col-lg-12">
    <?php echo $this->flashMessenger()->renderCurrent('default', array('alert', 'alert-success')); ?>
</div>

<div class="pull-right" style="margin-top: 10px; margin-bottom: 10px">
    <input type="button"
           onclick="location.href='<?php echo $this->url('admin/product', array('action' => 'color-add', 'product_id' => $product_id));?>'"
           class="btn btn-primary" value="Thêm">
</div>

<table class="table table-nomargin table-striped table-colored-header">
    <thead>
    <tr>
        <th>Hình ảnh</th>
        <th>Màu</th>
        <th>Trạng thái</th>
        <th>Chức năng</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($productDetails as $v) {?>
    <tr>
        <td>
            <?php
            if ($v['color_picture'] != '') {
                echo '<img src="' . $this->basePath('pictures/' . $v['color_picture']) . '" class="img-thumbnail" style="width: 50px; height: 50px" />';
            } else {
                echo '<img src="' . $this->basePath('pictures/no-image.gif') . '" class="img-thumbnail" style="width: 50px; height: 50px" />';
            }
            ?>
        </td>
        <td>
            <?php echo $this->escapeHtml($v['color_name']);?>
        </td>
        <td><?php echo $status[$v['product_detail_status']]; ?></td>
        <td>
            <a href="<?php echo $this->url('admin/product', array('action' => 'color-edit', 'product_id' => $product_id), array('query' => array('id' => $v['product_detail_id']))); ?>">
                <i class="icon-edit"></i>
            </a>
            <a onclick="return confirmDelete()"
               href="<?php echo $this->url('admin/product', array('action' => 'color-delete', 'product_id' => $product_id), array('query' => array('id' => $v['product_detail_id']))); ?>">
                <i class="icon-remove"></i>
            </a>
        </td>
    </tr>
    <?php }?>

    </tbody>
</table>

<script>
    function confirmDelete() {
        if (!confirm('Bạn có chắc chắn muốn xóa?')) {
            return false;
        }
    }
</script>
