<div class="page-header">
    <div class="pull-left">
        <h1>Sản phẩm</h1>
    </div>
</div>

<div class="col-lg-12">
    <?php echo $this->flashMessenger()->renderCurrent('default', array('alert', 'alert-success')); ?>
</div>



<div class="row-fluid">
    <div class="span12">
        <div class="box box-bordered box-color">
            <div class="box-title">
                <h3><i class="icon-edit"></i> <?php echo $actionTitle;?></h3>
            </div>
            <div class="box-content nopadding">
                <?php
                $form->setAttributes(['action' => '', 'class' => 'form-horizontal form-bordered', 'id' => 'frm']);
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>

                <div class="control-group">
                    <?php echo $this->formLabel($form->get('product_category_id')); ?>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('product_category_id')); ?>
                        <?php echo $this->formElementErrors($form->get('product_category_id'), array('class' => 'error-message')); ?>
                    </div>
                </div>

                    <div class="control-group">
                        <?php echo $this->formLabel($form->get('product_name')); ?>
                        <div class="controls">
                            <?php echo $this->formElement($form->get('product_name')); ?>
                            <?php echo $this->formElementErrors($form->get('product_name'), array('class' => 'error-message')); ?>
                        </div>
                    </div>

                <div class="control-group">
                    <?php echo $this->formLabel($form->get('product_code')); ?>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('product_code')); ?>
                        <?php echo $this->formElementErrors($form->get('product_code'), array('class' => 'error-message')); ?>
                    </div>
                </div>

                <div class="control-group">
                    <?php echo $this->formLabel($form->get('product_picture')); ?>
                    <div class="controls">


                        <?php echo $this->formElementErrors($form->get('product_picture'), array('class' => 'error-message')); ?>

                        <div class="fileupload fileupload-new" data-provides="fileupload">
                            <div class="fileupload-new thumbnail" style="width: 50px; height: 50px;">
                                <?php if (isset($record) && $record['product_picture'] != '') {?>
                                    <img title="Click để xóa" id="picture" onclick="deletePicture(<?php echo $record['product_id'];?>)" style="width: 50px; height: 50px; cursor: pointer" class="img-thumbnail" src="<?php echo $this->basePath('pictures/' . $record['product_picture']);?>" />
                                <?php } else {?>
                                    <img src="<?php echo $this->basePath('pictures/no-image.gif');?>" class="img-thumbnail" style="width: 50px; height: 50px" />
                                <?php }?>
                            </div>
                            <div class="fileupload-preview fileupload-exists thumbnail" style="width: 50px; height: 50px;"></div>
                            <div>
                                <span class="btn btn-file">
                                    <span class="fileupload-new">Chọn hình</span><span class="fileupload-exists">Thay đổi</span>
                                    <?php echo $this->formElement($form->get('product_picture')); ?></span>
                                <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Xóa</a>
                            </div>
                        </div>
                    </div>
                </div>


                <?php if (isset($id)) {?>
                    <div class="control-group">
                        <label class="control-label col-lg-2" for="product_status">Hình ảnh cho màu sản phẩm</label>
                        <div class="controls">
                            <input href="#myModal" type="button" class="btn btn-success" value="Cập nhật" data-toggle="modal">
                        </div>
                    </div>
                <?php }?>

                <div class="control-group">
                    <?php echo $this->formLabel($form->get('product_type_new')); ?>
                    <div class="controls">
                        <?php echo $this->formCheckbox($form->get('product_type_new')); ?>
                        <?php echo $this->formElementErrors($form->get('product_type_new'), array('class' => 'error-message')); ?>
                    </div>
                </div>

                <div class="control-group">
                    <?php echo $this->formLabel($form->get('product_type_sale')); ?>
                    <div class="controls">
                        <?php echo $this->formCheckbox($form->get('product_type_sale')); ?>
                        <?php echo $this->formElementErrors($form->get('product_type_sale'), array('class' => 'error-message')); ?>
                    </div>
                </div>

                <div class="control-group">
                    <?php echo $this->formLabel($form->get('product_price_old')); ?>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('product_price_old')); ?>
                        <?php echo $this->formElementErrors($form->get('product_price_old'), array('class' => 'error-message')); ?>
                    </div>
                </div>

                <div class="control-group">
                    <?php echo $this->formLabel($form->get('product_price')); ?>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('product_price')); ?>
                        <?php echo $this->formElementErrors($form->get('product_price'), array('class' => 'error-message')); ?>
                    </div>
                </div>



                    <div class="control-group">
                        <?php echo $this->formLabel($form->get('product_description')); ?>
                        <div class="controls">
                            <?php echo $this->formElement($form->get('product_description')); ?>
                            <?php echo $this->formElementErrors($form->get('product_description'), array('class' => 'error-message')); ?>
                        </div>
                    </div>



                <div class="control-group">
                    <?php echo $this->formLabel($form->get('product_status')); ?>
                    <div class="controls">
                        <?php echo $this->formElement($form->get('product_status')); ?>
                        <?php echo $this->formElementErrors($form->get('product_status'), array('class' => 'error-message')); ?>
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label col-lg-2" for="page_title">Url</label>
                    <div class="controls">
                        <strong><?php echo trim($this->url('home-product-detail', array('name' => $this->functions()->formatTitle($record['product_name']), 'id' => $record['product_id'])), '/');?></strong>
                    </div>
                </div>

                    <div class="form-actions">
                        <input onclick="location.href='<?php echo $this->url('admin/product');?>'" type="button" class="btn btn-default" value="Quay lại" data-toggle="modal">
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                        <?php echo $this->formHidden($form->get('csrf')); ?>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>

<style>
    .modal {
        width: 70%;
        margin: 0 auto;
        left: 15%;
        height: 80%;
    }
    .modal-body {
        height: 100%;
        max-height: 500px;
    }
</style>

<?php if (isset($id)) {?>
<!-- Modal -->
<div id="myModal" class="modal hide fade" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Hình ảnh cho màu sản phẩm</h3>
    </div>
    <div class="modal-body">
        <iframe style="border: 0; width: 100%; min-height: 450px" src="<?php echo $this->url('admin/product', array('action' => 'color', 'product_id' => $record['product_id']));?>"></iframe>
    </div>
</div>
<?php }?>

<script>
    $(document).ready(function(){
        $("#frm").validate({
            rules: {
                product_name: 'required',
            },
            messages: {
                product_name: 'Vui lòng nhập thông tin',
            }
        });
    });

    function deletePicture(id) {
        if (confirm('Bạn có muốn xóa?')) {
            $.ajax({
                url: '<?php echo $this->url('admin/product', array('action' => 'delete-picture'));?>',
                type: 'post',
                data: {id: id},
                success: function (response) {
                    data = jQuery.parseJSON(response);
                    if (data.return == 1) {
                        $('#picture').remove();
                    }
                }
            });
        }
    }
</script>