<div class="page-header">
    <div class="pull-left">
        <h1>Sản phẩm</h1>
    </div>
</div>


<div class="col-lg-12">
    <?php echo $this->flashMessenger()->renderCurrent('default', array('alert', 'alert-success')); ?>
</div>

<div class="row-fluid">
    <div class="span12">
        <div class="box box-bordered box-color">
            <div class="box-title">
                <h3><i class="icon-th-list"></i> Tìm kiếm</h3>
            </div>
            <div class="box-content nopadding">
                <form action="#" method="POST" class="form-horizontal form-column">
                    <div class="span6">
                        <div class="control-group">
                            <label for="textfield" class="control-label">Tên sản phẩm</label>

                            <div class="controls">
                                <input type="text" name="name" id="name" class="input-xlarge"
                                       value="<?php echo $search['name']; ?>">
                            </div>
                        </div>

                    </div>
                    <div class="span6">
                        <div class="control-group">
                            <label for="textfield" class="control-label">Danh mục</label>

                            <div class="controls">
                                <select name="category" class="input-xlarge">
                                    <option value="">Tất cả</option>
                                    <?php foreach ($productCategory as $v) { ?>
                                        <option <?php echo ($v['product_category_id'] == $search['category']) ? 'selected="selected"' : ''; ?>
                                            value="<?php echo $v['product_category_id']; ?>"><?php echo $v['product_category_name']; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="span12">
                        <div class="form-actions text-right" style="margin-top: 0; margin-bottom: 0; padding-top: 0">
                            <button type="submit" class="btn btn-primary">Tìm</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

<div class="pull-right" style="margin-top: 10px; margin-bottom: 10px">
    <input type="button"
           onclick="location.href='<?php echo $this->url('admin/product', array('action' => 'add')); ?>'"
           class="btn btn-primary" value="Thêm">
</div>

<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-nomargin table-striped table-colored-header">
                    <thead>
                    <tr>
                        <th>Hình ảnh</th>
                        <th>Tên sản phẩm</th>
                        <th>Danh mục</th>
                        <th>Giá</th>
                        <th>New</th>
                        <th>Sale</th>
                        <th>Trạng thái</th>
                        <th>Chức năng</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($records as $record) { ?>
                        <tr>
                            <td width="50px">
                                <?php
                                if ($record['product_picture'] != '') {
                                    echo '<img src="' . $this->basePath('pictures/' . $record['product_picture']) . '" class="img-thumbnail" style="width: 50px; height: 50px" />';
                                } else {
                                    echo '<img src="' . $this->basePath('pictures/no-image.gif') . '" class="img-thumbnail" style="width: 50px; height: 50px" />';
                                }
                                ?>
                            </td>
                            <td><strong><?php echo $this->escapeHtml($record['product_name']); ?></strong></td>
                            <td><?php echo $this->escapeHtml($record['product_category_name']); ?></td>
                            <td><?php echo $this->currency($record['product_price']);?></td>
                            <td><i class="<?php echo ($record['product_type_new'] == 1) ? 'icon-check' : 'icon-check-empty';?>"></i></td>
                            <td><i class="<?php echo ($record['product_type_sale'] == 1) ? 'icon-check' : 'icon-check-empty';?>"></i></td>
                            <td><?php echo $status[$record['product_status']]; ?></td>
                            <td>
                                <a href="<?php echo $this->url('admin/product', array('action' => 'edit'), array('query' => array('id' => $record['product_id']))); ?>">
                                    <i class="icon-edit"></i>
                                </a>
                                <a onclick="return confirmDelete()"
                                   href="<?php echo $this->url('admin/product', array('action' => 'delete'), array('query' => array('id' => $record['product_id']))); ?>">
                                    <i class="icon-remove"></i>
                                </a>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
                <div class="form-actions no-margin-bottom"
                     style="text-align:right; margin-top: 0; margin-bottom: 0; padding-top: 0; padding-bottom: 0">
                    <?php echo $this->paginationControl($records, 'sliding', 'admin/partial/paginator', array('url' => $this->url('admin/product'),)); ?>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function confirmDelete() {
        if (!confirm('Bạn có chắc chắn muốn xóa?')) {
            return false;
        }
    }
</script>
